---
title: "RIPTIDE Metabolite Flux"
author: "Kathleen L. Furtado"
date: "2023-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=TRUE}
#Load necesary libraries for session
#Session run under R 4.3.2
library(reshape2)
library(ggplot2)
```

## Determining uptake/efflux of specific metabolites after RIPTiDe maxfit contextualization
```{r fluxes, include=TRUE}
#Set seed for reproducibility
set.seed(13)

#Read in data from riptide.maxfit_contextualize
cdmm_fluxes <- read.delim('~/RIPTIDE/riptide_cdmm_max_complete/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)
iec_fluxes <- read.delim('~/RIPTIDE/riptide_iec_max_complete/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)

#Subsample to 250 samplings, or minimum number for any condition.
sample_size <- min(c(nrow(cdmm_fluxes), nrow(iec_fluxes), 250))
sub_sample <- sample(1:min(c(nrow(cdmm_fluxes), nrow(iec_fluxes))), sample_size, replace=FALSE)
cdmm_fluxes <- cdmm_fluxes[sub_sample,]
iec_fluxes <- iec_fluxes[sub_sample,]
rm(sample_size, sub_sample)

#Overall Biomass----------------------------------------
cdmm_biomass <- as.vector(cdmm_fluxes[,'biomass']) 
iec_biomass <- as.vector(iec_fluxes[,'biomass']) 
mean(cdmm_biomass)
mean(iec_biomass)
sd(cdmm_biomass)
sd(iec_biomass)

#Test normality of distributions
shapiro.test(cdmm_biomass)$p.value #not normal
shapiro.test(iec_biomass)$p.value #not normal

#Test differences in biomass
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_biomass, size=12)
  test_2 <- sample(iec_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_pval <- round(median(pvals), 4) #p=0.000004; significant

#Biomass Vplot
biomass <- data.frame(cdmm_biomass, iec_biomass)
colnames(biomass) <- c("No Mucus", "IEC Mucus")
biomass <- melt(biomass)
colnames(biomass) <- c("Mucus", "Biomass")
biomass_vplot <- ggplot(biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "IEC Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(biomass$Biomass), label="****", hjust="center", vjust="top", size=8)
biomass_vplot

ggsave(file="Biomass_Violin.svg", plot=biomass_vplot, width=4, height=4, dpi=300)

##Determine uptake/efflux for metabolites of interest
#Glycine-------------------------------------------------------
#see increased gly synthesis from serine and 5,10-methylene-THF with mucus
#cdmm_gly_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00033_e']) * -1.0 #pruned; no uptake or efflux
#iec_gly_uptake <- as.vector(iec_fluxes[,'EX_cpd00033_e']) * -1.0 #pruned; no uptake or efflux

#Serine--------------------------------------------------------
#See increased conversion of serine to glycine in mucus
#cdmm_ser_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00054_e']) * -1.0 #pruned; no uptake or efflux
iec_ser_uptake <- as.vector(iec_fluxes[,'EX_cpd00054_e']) * -1.0
mean(iec_ser_uptake) #7.415264
sd(iec_ser_uptake)
#Assess distribution
shapiro.test(iec_ser_uptake)$p.value #not normal

#Serine Vplot
cdmm_ser_null <- rep(0, 250)
serine <- data.frame(cdmm_ser_null, iec_ser_uptake)
colnames(serine) <- c("None", "IEC Mucus")
serine <- melt(serine)
colnames(serine) <- c("Mucus", "Uptake")
serine <- serine[-c(1:249),] #removes all but one sample; allows condition without mucus to be "plotted" without disrupting appearance of IEC Mucus violin distribution.
serine_vplot <- ggplot(serine, aes(x=Mucus, y=Uptake, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("None" = "#332288", "IEC Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1, y=1.5, label="No Uptake", hjust="center", vjust="top", size=5)
serine_vplot

ggsave(file="Serine_Violin.svg", plot=serine_vplot, width=3, height=4, dpi=300)

#Aspartate---------------------------------------------------------
#See production of dihydrodipicolinate from L-Asp-4-semialdehyde; precursor to lysine biosynthesis
cdmm_asp_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00041_e']) * -1.0
iec_asp_uptake <- as.vector(iec_fluxes[,'EX_cpd00041_e']) * -1.0
mean(cdmm_asp_uptake) #369.9667
mean(iec_asp_uptake) #207.3622
#Assess distributions
shapiro.test(cdmm_asp_uptake)$p.value #not normal
shapiro.test(iec_asp_uptake)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_asp_uptake, size=12)
  test_2 <- sample(iec_asp_uptake, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
asp_pval <- round(median(pvals), 4) #p=0.0351; significant!

#Aspartate Vplot
asp <- data.frame(cdmm_asp_uptake, iec_asp_uptake)
colnames(asp) <- c("No Mucus", "Mucus")
asp <- melt(asp)
colnames(asp) <- c("Mucus", "Uptake")
asp_vplot <- ggplot(asp, aes(x=Mucus, y=Uptake, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(asp$Uptake), label="*", hjust="center", vjust="top", size=8)
asp_vplot
ggsave(file="Asp_Violin.svg", plot=asp_vplot, width=3, height=4, dpi=300)

#L-glutamate------------------------------------------------------------- 
#see conversion from 2-oxoglutarate to NAD+ and glutamate with mucus
cdmm_glu_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00023_e']) * -1.0
iec_glu_uptake <- as.vector(iec_fluxes[,'EX_cpd00023_e']) * -1.0
mean(cdmm_glu_uptake) #-37.99017; more L-glutamate efflux
mean(iec_glu_uptake) #28.56968; more L-glutamate uptake
#Assess distributions
shapiro.test(cdmm_glu_uptake)$p.value #not normal
shapiro.test(iec_glu_uptake)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_glu_uptake, size=12)
  test_2 <- sample(iec_glu_uptake, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
glu_pval <- round(median(pvals), 4) #p=0.0001; significant!

#Glutamate Vplot
glu <- data.frame(cdmm_glu_uptake, iec_glu_uptake)
colnames(glu) <- c("No Mucus", "Mucus")
glu <- melt(glu)
colnames(glu) <- c("Mucus", "Uptake")
glu_vplot <- ggplot(glu, aes(x=Mucus, y=Uptake, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(glu$Uptake), label="***", hjust="center", vjust="top", size=8)
glu_vplot
ggsave(file="Glu_Violin.svg", plot=glu_vplot, width=3, height=4, dpi=300)

#L-alanine-------------------------------------------------------
#see increased uptake and conversion to pyruvate with mucus
cdmm_ala_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00035_e']) * -1.0
iec_ala_uptake <- as.vector(iec_fluxes[,'EX_cpd00035_e']) * -1.0
mean(cdmm_ala_uptake) #174.7038
mean(iec_ala_uptake) #674.6835
#Assess distributions
shapiro.test(cdmm_ala_uptake)$p.value #not normal
shapiro.test(iec_ala_uptake)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_ala_uptake, size=12)
  test_2 <- sample(iec_ala_uptake, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
ala_pval <- round(median(pvals), 4) #p=0.0001; significant!

#Alanine Vplot
ala <- data.frame(cdmm_ala_uptake, iec_ala_uptake)
colnames(ala) <- c("No Mucus", "Mucus")
ala <- melt(ala)
colnames(ala) <- c("Mucus", "Uptake")
ala_vplot <- ggplot(ala, aes(x=Mucus, y=Uptake, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(ala$Uptake), label="***", hjust="center", vjust="top", size=8)
ala_vplot
ggsave(file="Ala_Violin.svg", plot=ala_vplot, width=3, height=4, dpi=300)

#N-acetyl-D-glucosamine (GlcNAc)------------------------------------------------
#uptake only allowed for mucus condition, but see flux in pathways containing this metabolite both with and without mucus
cdmm_glcNAc_efflux <- as.vector(cdmm_fluxes[,'EX_cpd00122_e']) 
iec_glcNAc_efflux <- as.vector(iec_fluxes[,'EX_cpd00122_e']) 
mean(cdmm_glcNAc_efflux) #137.79
mean(iec_glcNAc_efflux) #711.7133
sd(cdmm_glcNAc_efflux)
sd(iec_glcNAc_efflux)
#Assess distributions
shapiro.test(cdmm_glcNAc_efflux)$p.value #not normal
shapiro.test(iec_glcNAc_efflux)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_glcNAc_efflux, size=12)
  test_2 <- sample(iec_glcNAc_efflux, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
glcNAc_pval <- round(median(pvals), 4) #p=0.0003; significant!

#GlcNAc Vplot
glcNAc <- data.frame(cdmm_glcNAc_efflux, iec_glcNAc_efflux)
colnames(glcNAc) <- c("No Mucus", "Mucus")
glcNAc <- melt(glcNAc)
colnames(glcNAc) <- c("Mucus", "Efflux")
glcNAc_vplot <- ggplot(glcNAc, aes(x=Mucus, y=Efflux, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(glcNAc$Efflux), label="***", hjust="center", vjust="top", size=8)
glcNAc_vplot
ggsave(file="GlcNAc_Violin.svg", plot=glcNAc_vplot, width=3, height=4, dpi=300)

##Decide whether or not other metabolites (Acetate, Butyrate, Pro, Thr, Glc) are useful--------------------------------------------

#Acetate: downstream product from glycine stickland metabolism
#also exported from WLP
cdmm_acetate_efflux <- as.vector(cdmm_fluxes[,'EX_cpd00029_e'])
iec_acetate_efflux <- as.vector(iec_fluxes[,'EX_cpd00029_e'])
mean(cdmm_acetate_efflux) #211.5813
mean(iec_acetate_efflux) #438.1394
#Assess distributions
shapiro.test(cdmm_acetate_efflux)$p.value #not normal
shapiro.test(iec_acetate_efflux)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_acetate_efflux, size=12)
  test_2 <- sample(iec_acetate_efflux, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
acetate_pval <- round(median(pvals), 4) #p=0.0094; significant!

#butyrate exported from WLP
#cdmm_but_efflux <- as.vector(cdmm_fluxes[,'R_EX_cpd00211_e']) #pruned
#iec_but_efflux <- as.vector(iec_fluxes[,'R_EX_cpd00211_e']) #pruned

#proline- another important stickland metabolite. Also important feature in backbone of mucus  
cdmm_pro_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00129_e']) * -1.0
iec_pro_uptake <- as.vector(iec_fluxes[,'EX_cpd00129_e']) * -1.0
mean(cdmm_pro_uptake) #57.84925 #fits observations of increased proline stickland fermentation without mucus?
mean(iec_pro_uptake) #1.967352
sd(cdmm_pro_uptake)
sd(iec_pro_uptake)
#Assess distributions
shapiro.test(cdmm_pro_uptake)$p.value #not normal
shapiro.test(iec_pro_uptake)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_pro_uptake, size=12)
  test_2 <- sample(iec_pro_uptake, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
pro_pval <- round(median(pvals), 4) #p=0.014; significant!

#Pro Vplot
pro <- data.frame(cdmm_pro_uptake, iec_pro_uptake)
colnames(pro) <- c("No Mucus", "Mucus")
pro <- melt(pro)
colnames(pro) <- c("Mucus", "Uptake")
pro_vplot <- ggplot(pro, aes(x=Mucus, y=Uptake, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  scale_y_continuous(trans="log10")+
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(pro$Uptake), label="*", hjust="center", vjust="top", size=8)
pro_vplot
ggsave(file="Pro_Violin.svg", plot=pro_vplot, width=3, height=4, dpi=300)

#threonine is remaining part of protein backbone unexplored; threonine exchange also shows up in MDA
cdmm_thr_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00161_e']) * -1.0
iec_thr_uptake <- as.vector(iec_fluxes[,'EX_cpd00161_e']) * -1.0
mean(cdmm_thr_uptake) #2.316037
mean(iec_thr_uptake) #3.561337
sd(cdmm_thr_uptake)
sd(iec_thr_uptake)
#Assess distributions
shapiro.test(cdmm_thr_uptake)$p.value #not normal
shapiro.test(iec_thr_uptake)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_thr_uptake, size=12)
  test_2 <- sample(iec_thr_uptake, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
thr_pval <- round(median(pvals), 4) #p=0.0005; significant!
#Thr Vplot
thr <- data.frame(cdmm_thr_uptake, iec_thr_uptake)
colnames(thr) <- c("No Mucus", "Mucus")
thr <- melt(thr)
colnames(thr) <- c("Mucus", "Uptake")
thr_vplot <- ggplot(thr, aes(x=Mucus, y=Uptake, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(thr$Uptake), label="***", hjust="center", vjust="top", size=8)
thr_vplot
ggsave(file="thr_Violin.svg", plot=thr_vplot, width=3, height=4, dpi=300)

#C.d. may depend more on glucose with activation of WLP
cdmm_glc_uptake <- as.vector(cdmm_fluxes[,'EX_cpd00027_e']) * -1.0
iec_glc_uptake <- as.vector(iec_fluxes[,'EX_cpd00027_e']) * -1.0
mean(cdmm_glc_uptake) #223.6629
mean(iec_glc_uptake) #226.4078
#Assess distributions
shapiro.test(cdmm_glc_uptake)$p.value #not normal
shapiro.test(iec_glc_uptake)$p.value #not normal
#Differences
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_glc_uptake, size=12)
  test_2 <- sample(iec_glc_uptake, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
glc_pval <- round(median(pvals), 4) #p=0.4705; not significant


#Doubling Times--------------------------------------------------
#How to determine doubling times. Model has 3600 seconds defined as growth period, hence * 3600 used here.
cdmm_doubling <- (1/cdmm_biomass) * 3600.0
iec_doubling <- (1/iec_biomass) * 3600.0
mean(cdmm_doubling) #169.7202
mean(iec_doubling) #104.0111 C. difficile doubles faster with mucus.

#Doubling Time Vplot
dbl <- data.frame(cdmm_doubling, iec_doubling)
colnames(dbl) <- c("No Mucus", "Mucus")
dbl <- melt(dbl)
colnames(dbl) <- c("Mucus", "DoublingTime")
dbl_vplot <- ggplot(dbl, aes(x=Mucus, y=DoublingTime, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(dbl$DoublingTime), label="***", hjust="center", vjust="top", size=8)
dbl_vplot
```

## Confirm biomass differences are true, and not due to inclusion of mucus monosaccharide exchanges in mucus condition only
```{r monosacc_test, include=TRUE}
set.seed(13)

# Read in data
cdmm_mono_fluxes <- read.delim('~/RIPTIDE/riptide_cdmm_monosacc_test_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)

#Subsample IEC mucus condition to same number of samples as CDMM condition
sample_size <- min(c(nrow(cdmm_mono_fluxes), nrow(iec_fluxes), 250))
sub_sample <- sample(1:min(c(nrow(cdmm_mono_fluxes), nrow(iec_fluxes))), sample_size, replace=FALSE)
cdmm_mono_fluxes <- cdmm_mono_fluxes[sub_sample,]
iec_check_fluxes <- iec_fluxes[sub_sample,]
rm(sample_size, sub_sample)

#New Biomass
cdmm_mono_biomass <- as.vector(cdmm_mono_fluxes[,'biomass'])
iec_check_biomass <- as.vector(iec_check_fluxes[,'biomass'])
mean(cdmm_mono_biomass) #23.88783
mean(iec_check_biomass) #35.90058
sd(cdmm_mono_biomass)

#Confirm p-value:
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_mono_biomass, size=12)
  test_2 <- sample(iec_check_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_mono_pval <- round(median(pvals), 4) #p-0.0007, still significant!

#New violin plot
biomass_mono <- data.frame(cdmm_mono_biomass, iec_check_biomass)
colnames(biomass_mono) <- c("No Mucus", "IEC Mucus")
biomass_mono <- melt(biomass_mono)
colnames(biomass_mono) <- c("Mucus", "Biomass")

biomass_mono_vplot <- ggplot(biomass_mono, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  theme_bw() +
  scale_fill_manual(values=c("No Mucus" = "#332288", "IEC Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(biomass_mono$Biomass), label="***", hjust="center", vjust="top", size=8)
biomass_mono_vplot
```


## Check biomasses from subsequent experimental conditions and effect on model:
```{r expt_cond, include=TRUE}
#Set seed for reproducibility
set.seed(13)

##Conditions without glycine or serine--------------------------------

#Read in data from riptide.maxfit_contextualize
cdmm_noGS_fluxes <- read.delim('~/RIPTIDE/riptide_cdmm_no_gs_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)
iec_noGS_fluxes <- read.delim('~/RIPTIDE/riptide_iec_no_gs_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)

#Subsample to 250 samplings, or minimum number for any condition.
sample_size <- min(c(nrow(cdmm_noGS_fluxes), nrow(iec_noGS_fluxes), 250))
sub_sample <- sample(1:min(c(nrow(cdmm_noGS_fluxes), nrow(iec_noGS_fluxes))), sample_size, replace=FALSE)
cdmm_noGS_fluxes <- cdmm_noGS_fluxes[sub_sample,]
iec_noGS_fluxes <- iec_noGS_fluxes[sub_sample,]
rm(sample_size, sub_sample)

#Overall Biomass
cdmm_noGS_biomass <- as.vector(cdmm_noGS_fluxes[,'biomass'])
iec_noGS_biomass <- as.vector(iec_noGS_fluxes[,'biomass'])
median(cdmm_noGS_biomass) #25.59558
median(iec_noGS_biomass) #35.08974

#Test normality of distributions
shapiro.test(cdmm_noGS_biomass)$p.value #not normal
shapiro.test(iec_noGS_biomass)$p.value #not normal

#Test differences in biomass between mucus (no GS) and no mucus (no GS)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_noGS_biomass, size=12)
  test_2 <- sample(iec_noGS_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noGS_pval <- round(median(pvals), 4) #p=0.002; significant!

#Test differences in biomass between mucus (no GS) and mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(iec_biomass, size=12)
  test_2 <- sample(iec_noGS_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noGS_p_muc <- round(median(pvals), 4) #p=0.544; not significant

#Test differences in biomass between no mucus (no GS) and no mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_biomass, size=12)
  test_2 <- sample(cdmm_noGS_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noGS_p_nomuc <- round(median(pvals), 4) #p=0.3707; not significant

##Violin plots:
#Biomass -GS Vplot
noGS_biomass <- data.frame(cdmm_noGS_biomass, iec_noGS_biomass)
colnames(noGS_biomass) <- c("No Mucus", "IEC Mucus")
noGS_biomass <- melt(noGS_biomass)
colnames(noGS_biomass) <- c("Mucus", "Biomass")

noGS_biomass_vplot <- ggplot(noGS_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "IEC Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(noGS_biomass$Biomass), label="**", hjust="center", vjust="top", size=8)
noGS_biomass_vplot

#Biomass Muc Complete vs. Muc -GS Vplot:
muc_noGS_biomass <- data.frame(iec_biomass, iec_noGS_biomass)
colnames(muc_noGS_biomass) <- c("Complete +Mucus", "-GS +Mucus")
muc_noGS_biomass <- melt(muc_noGS_biomass)
colnames(muc_noGS_biomass) <- c("Mucus", "Biomass")

muc_noGS_biomass_vplot <- ggplot(muc_noGS_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete +Mucus" = "#5AAE61", "-GS +Mucus" = "#D9F0D3")) +
  annotate(geom="text", x= 1.5, y=max(muc_noGS_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
muc_noGS_biomass_vplot

#Biomass No Muc Complete vs. No Muc -GS Vplot:
nomuc_noGS_biomass <- data.frame(cdmm_biomass, cdmm_noGS_biomass)
colnames(nomuc_noGS_biomass) <- c("Complete", "-GS")
nomuc_noGS_biomass <- melt(nomuc_noGS_biomass)
colnames(nomuc_noGS_biomass) <- c("Mucus", "Biomass")

nomuc_noGS_biomass_vplot <- ggplot(nomuc_noGS_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-GS" = "#77AADD")) +
  annotate(geom="text", x= 1.5, y=max(nomuc_noGS_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
nomuc_noGS_biomass_vplot

#Put all 4 conditions on one plot:
noGS_all_biomass <- data.frame(cdmm_biomass, cdmm_noGS_biomass, iec_biomass, iec_noGS_biomass)
colnames(noGS_all_biomass) <- c("Complete", "-GS", "Complete +Mucus", "-GS +Mucus")
noGS_all_biomass <- melt(noGS_all_biomass)
colnames(noGS_all_biomass) <- c("Media", "Biomass")

noGS_all_biomass_vplot <- ggplot(noGS_all_biomass, aes(x=Media, y=Biomass, fill=Media)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-GS" = "#77AADD", "Complete +Mucus" = "#5AAE61", "-GS +Mucus"="#ACD39E")) +
  annotate(geom="text", x= 1.5, y=max(noGS_all_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 3.5, y=max(noGS_all_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
noGS_all_biomass_vplot

##Conditions without glycine---------------------------------------------

#Read in data from riptide.maxfit_contextualize
cdmm_noG_fluxes <- read.delim('~/RIPTIDE/riptide_cdmm_no_g_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)
iec_noG_fluxes <- read.delim('~/RIPTIDE/riptide_iec_no_g_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)

#Subsample to 250 samplings, or minimum number for any condition.
sample_size <- min(c(nrow(cdmm_noG_fluxes), nrow(iec_noG_fluxes), 250))
sub_sample <- sample(1:min(c(nrow(cdmm_noG_fluxes), nrow(iec_noG_fluxes))), sample_size, replace=FALSE)
cdmm_noG_fluxes <- cdmm_noG_fluxes[sub_sample,]
iec_noG_fluxes <- iec_noG_fluxes[sub_sample,]
rm(sample_size, sub_sample)

#Overall Biomass
cdmm_noG_biomass <- as.vector(cdmm_noG_fluxes[,'biomass']) 
iec_noG_biomass <- as.vector(iec_noG_fluxes[,'biomass'])
median(cdmm_noG_biomass) #23.67973
median(iec_noG_biomass) #35.10179

#Test normality of distributions
shapiro.test(cdmm_noG_biomass)$p.value #not normal
shapiro.test(iec_noG_biomass)$p.value #not normal

#Test differences in biomass between mucus (no G) and no mucus (no G)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_noG_biomass, size=12)
  test_2 <- sample(iec_noG_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noG_pval <- round(median(pvals), 4) #p=0.0011; significant!

#Test differences in biomass between mucus (no G) and mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(iec_biomass, size=12)
  test_2 <- sample(iec_noG_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noG_p_muc <- round(median(pvals), 4) #p=0.5042; not significant

#Test differences in biomass between no mucus (no G) and no mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_biomass, size=12)
  test_2 <- sample(cdmm_noG_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noG_p_nomuc <- round(median(pvals), 4) #p=0.5067; not significant

##Violin plots:
#Biomass -G Vplot
noG_biomass <- data.frame(cdmm_noG_biomass, iec_noG_biomass)
colnames(noG_biomass) <- c("No Mucus", "IEC Mucus")
noG_biomass <- melt(noG_biomass)
colnames(noG_biomass) <- c("Mucus", "Biomass")

noG_biomass_vplot <- ggplot(noG_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "IEC Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(noG_biomass$Biomass), label="**", hjust="center", vjust="top", size=8)
noG_biomass_vplot

#Biomass Muc Complete vs. Muc -G Vplot:
muc_noG_biomass <- data.frame(iec_biomass, iec_noG_biomass)
colnames(muc_noG_biomass) <- c("Complete +Mucus", "-G +Mucus")
muc_noG_biomass <- melt(muc_noG_biomass)
colnames(muc_noG_biomass) <- c("Mucus", "Biomass")

muc_noG_biomass_vplot <- ggplot(muc_noG_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete +Mucus" = "#5AAE61", "-G +Mucus" = "#D9F0D3")) +
  annotate(geom="text", x= 1.5, y=max(muc_noG_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
muc_noG_biomass_vplot

#Biomass No Muc Complete vs. No Muc -G Vplot:
nomuc_noG_biomass <- data.frame(cdmm_biomass, cdmm_noG_biomass)
colnames(nomuc_noG_biomass) <- c("Complete", "-G")
nomuc_noG_biomass <- melt(nomuc_noG_biomass)
colnames(nomuc_noG_biomass) <- c("Mucus", "Biomass")

nomuc_noG_biomass_vplot <- ggplot(nomuc_noG_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-G" = "#77AADD")) +
  annotate(geom="text", x= 1.5, y=max(nomuc_noG_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
nomuc_noG_biomass_vplot

#Put all 4 conditions on one plot:
noG_all_biomass <- data.frame(cdmm_biomass, cdmm_noG_biomass, iec_biomass, iec_noG_biomass)
colnames(noG_all_biomass) <- c("Complete", "-G", "Complete +Mucus", "-G +Mucus")
noG_all_biomass <- melt(noG_all_biomass)
colnames(noG_all_biomass) <- c("Media", "Biomass")

noG_all_biomass_vplot <- ggplot(noG_all_biomass, aes(x=Media, y=Biomass, fill=Media)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-G" = "#77AADD", "Complete +Mucus" = "#5AAE61", "-G +Mucus"="#ACD39E")) +
  annotate(geom="text", x= 1.5, y=max(noG_all_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 3.5, y=max(noG_all_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
noG_all_biomass_vplot


##Conditions without serine------------------------------------------------------
#Read in data from riptide.maxfit_contextualize
cdmm_noS_fluxes <- read.delim('~/RIPTIDE/riptide_cdmm_no_s_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)
iec_noS_fluxes <- read.delim('~/RIPTIDE/riptide_iec_no_s_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)

#Subsample to 250 samplings, or minimum number for any condition.
sample_size <- min(c(nrow(cdmm_noS_fluxes), nrow(iec_noS_fluxes), 250))
sub_sample <- sample(1:min(c(nrow(cdmm_noS_fluxes), nrow(iec_noS_fluxes))), sample_size, replace=FALSE)
cdmm_noS_fluxes <- cdmm_noS_fluxes[sub_sample,]
iec_noS_fluxes <- iec_noS_fluxes[sub_sample,]
rm(sample_size, sub_sample)

#Overall Biomass
cdmm_noS_biomass <- as.vector(cdmm_noS_fluxes[,'biomass']) #mean
iec_noS_biomass <- as.vector(iec_noS_fluxes[,'biomass'])
median(cdmm_noS_biomass) #25.87345
median(iec_noS_biomass) #35.39751

#Test normality of distributions
shapiro.test(cdmm_noS_biomass)$p.value #not normal
shapiro.test(iec_noS_biomass)$p.value #not normal

#Test differences in biomass between mucus (no S) and no mucus (no S)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_noS_biomass, size=12)
  test_2 <- sample(iec_noS_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noS_pval <- round(median(pvals), 4) #p=0.002; significant!

#Test differences in biomass between mucus (no S) and mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(iec_biomass, size=12)
  test_2 <- sample(iec_noS_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noS_p_muc <- round(median(pvals), 4) #p=0.5063; not significant

#Test differences in biomass between no mucus (no S) and no mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_biomass, size=12)
  test_2 <- sample(cdmm_noS_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noS_p_nomuc <- round(median(pvals), 4) #p=0.3122; not significant

##Violin plots:
#Biomass -S Vplot
noS_biomass <- data.frame(cdmm_noS_biomass, iec_noS_biomass)
colnames(noS_biomass) <- c("No Mucus", "IEC Mucus")
noS_biomass <- melt(noS_biomass)
colnames(noS_biomass) <- c("Mucus", "Biomass")

noS_biomass_vplot <- ggplot(noS_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "IEC Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(noS_biomass$Biomass), label="**", hjust="center", vjust="top", size=8)
noS_biomass_vplot

#Biomass Muc Complete vs. Muc -S Vplot:
muc_noS_biomass <- data.frame(iec_biomass, iec_noS_biomass)
colnames(muc_noS_biomass) <- c("Complete +Mucus", "-S +Mucus")
muc_noS_biomass <- melt(muc_noS_biomass)
colnames(muc_noS_biomass) <- c("Mucus", "Biomass")

muc_noS_biomass_vplot <- ggplot(muc_noS_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete +Mucus" = "#5AAE61", "-S +Mucus" = "#D9F0D3")) +
  annotate(geom="text", x= 1.5, y=max(muc_noS_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
muc_noS_biomass_vplot

#Biomass No Muc Complete vs. No Muc -S Vplot:
nomuc_noS_biomass <- data.frame(cdmm_biomass, cdmm_noS_biomass)
colnames(nomuc_noS_biomass) <- c("Complete", "-S")
nomuc_noS_biomass <- melt(nomuc_noS_biomass)
colnames(nomuc_noS_biomass) <- c("Mucus", "Biomass")

nomuc_noS_biomass_vplot <- ggplot(nomuc_noS_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-S" = "#77AADD")) +
  annotate(geom="text", x= 1.5, y=max(nomuc_noS_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
nomuc_noS_biomass_vplot

#Put all 4 conditions on one plot:
noS_all_biomass <- data.frame(cdmm_biomass, cdmm_noS_biomass, iec_biomass, iec_noS_biomass)
colnames(noS_all_biomass) <- c("Complete", "-S", "Complete +Mucus", "-S +Mucus")
noS_all_biomass <- melt(noS_all_biomass)
colnames(noS_all_biomass) <- c("Media", "Biomass")

noS_all_biomass_vplot <- ggplot(noS_all_biomass, aes(x=Media, y=Biomass, fill=Media)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-S" = "#77AADD", "Complete +Mucus" = "#5AAE61", "-S +Mucus"="#ACD39E")) +
  annotate(geom="text", x= 1.5, y=max(noS_all_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 3.5, y=max(noS_all_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
noS_all_biomass_vplot

##Conditions without Threonine--------------------------------------------------------------
#Read in data from riptide.maxfit_contextualize
cdmm_noT_fluxes <- read.delim('~/RIPTIDE/riptide_cdmm_no_t_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)
iec_noT_fluxes <- read.delim('~/RIPTIDE/riptide_iec_no_t_max/flux_samples.tsv', sep='\t', header=TRUE, row.names=1)

#Subsample to 250 samplings, or minimum number for any condition.
sample_size <- min(c(nrow(cdmm_noT_fluxes), nrow(iec_noT_fluxes), 250))
sub_sample <- sample(1:min(c(nrow(cdmm_noT_fluxes), nrow(iec_noT_fluxes))), sample_size, replace=FALSE)
cdmm_noT_fluxes <- cdmm_noT_fluxes[sub_sample,]
iec_noT_fluxes <- iec_noT_fluxes[sub_sample,]
rm(sample_size, sub_sample)

#Overall Biomass
cdmm_noT_biomass <- as.vector(cdmm_noT_fluxes[,'biomass']) #mean
iec_noT_biomass <- as.vector(iec_noT_fluxes[,'biomass'])
median(cdmm_noT_biomass) #24.21486
median(iec_noT_biomass) #27.62685

#Test normality of distributions
shapiro.test(cdmm_noT_biomass)$p.value #not normal
shapiro.test(iec_noT_biomass)$p.value #not normal

#Test differences in biomass between mucus (no T) and no mucus (no T)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_noT_biomass, size=12)
  test_2 <- sample(iec_noT_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noT_pval <- round(median(pvals), 4) #p=0.00885; not significant

#Test differences in biomass between mucus (no T) and mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(iec_biomass, size=12)
  test_2 <- sample(iec_noT_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noT_p_muc <- round(median(pvals), 4) #p=0.0166; significant!

#Test differences in biomass between no mucus (no T) and no mucus (complete)
pvals <- c()
for (x in c(1:1000)) {
  test_1 <- sample(cdmm_biomass, size=12)
  test_2 <- sample(cdmm_noT_biomass, size=12)
  pvals[x] <- wilcox.test(test_1, test_2, exact=FALSE)$p.value}
biomass_noT_p_nomuc <- round(median(pvals), 4) #p=0.5444; not significant

##Violin plots:
#Biomass -T Vplot
noT_biomass <- data.frame(cdmm_noT_biomass, iec_noT_biomass)
colnames(noT_biomass) <- c("No Mucus", "IEC Mucus")
noT_biomass <- melt(noT_biomass)
colnames(noT_biomass) <- c("Mucus", "Biomass")

noT_biomass_vplot <- ggplot(noT_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("No Mucus" = "#332288", "IEC Mucus" = "#5AAE61")) +
  annotate(geom="text", x= 1.5, y=max(noT_biomass$Biomass), label="p=0.0885", hjust="center", vjust="top", size=8)
noT_biomass_vplot

#Biomass Muc Complete vs. Muc -T Vplot:
muc_noT_biomass <- data.frame(iec_biomass, iec_noT_biomass)
colnames(muc_noT_biomass) <- c("Complete +Mucus", "-T +Mucus")
muc_noT_biomass <- melt(muc_noT_biomass)
colnames(muc_noT_biomass) <- c("Mucus", "Biomass")

muc_noT_biomass_vplot <- ggplot(muc_noT_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete +Mucus" = "#5AAE61", "-T +Mucus" = "#D9F0D3")) +
  annotate(geom="text", x= 1.5, y=max(muc_noT_biomass$Biomass), label="*", hjust="center", vjust="top", size=8)
muc_noT_biomass_vplot

#Biomass No Muc Complete vs. No Muc -T Vplot:
nomuc_noT_biomass <- data.frame(cdmm_biomass, cdmm_noT_biomass)
colnames(nomuc_noT_biomass) <- c("Complete", "-T")
nomuc_noT_biomass <- melt(nomuc_noT_biomass)
colnames(nomuc_noT_biomass) <- c("Mucus", "Biomass")

nomuc_noT_biomass_vplot <- ggplot(nomuc_noT_biomass, aes(x=Mucus, y=Biomass, fill=Mucus)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-T" = "#77AADD")) +
  annotate(geom="text", x= 1.5, y=max(nomuc_noT_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8)
nomuc_noT_biomass_vplot

#Put all 4 conditions on one plot:
noT_all_biomass <- data.frame(cdmm_biomass, cdmm_noT_biomass, iec_biomass, iec_noT_biomass)
colnames(noT_all_biomass) <- c("Complete", "-T", "Complete +Mucus", "-T +Mucus")
noT_all_biomass <- melt(noT_all_biomass)
colnames(noT_all_biomass) <- c("Media", "Biomass")

noT_all_biomass_vplot <- ggplot(noT_all_biomass, aes(x=Media, y=Biomass, fill=Media)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  stat_summary(fun = median, 
          geom = "point",
          color="white") +
  scale_fill_manual(values=c("Complete" = "#004488", "-T" = "#77AADD", "Complete +Mucus" = "#5AAE61", "-T +Mucus"="#ACD39E")) +
  annotate(geom="text", x= 1.5, y=max(noT_all_biomass$Biomass), label="ns", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 3.5, y=max(noT_all_biomass$Biomass), label="*", hjust="center", vjust="top", size=8)
noT_all_biomass_vplot
```

```{r compile_image, include=TRUE}
all_cond_biomass <- data.frame(cdmm_biomass, iec_biomass, cdmm_noGS_biomass, iec_noGS_biomass, cdmm_noS_biomass, iec_noS_biomass, cdmm_noG_biomass, iec_noG_biomass, cdmm_noT_biomass, iec_noT_biomass)
colnames(all_cond_biomass) <- c("Complete", "Complete +Mucus", "-G -S", "-G -S +Mucus", "-S", "-S +Mucus", "-G", "-G +Mucus", "-T", "-T +Mucus")
all_cond_biomass <- melt(all_cond_biomass)
colnames(all_cond_biomass) <- c("Media", "Biomass")

all_biomass_vplot <- ggplot(all_cond_biomass, aes(x=Media, y=Biomass, fill=Media, color=Media)) +
  geom_violin(trim=FALSE) +
  theme_bw() +
  theme(legend.position='none') +
  stat_summary(fun = median, 
          geom = "point",
          color="black") +
  scale_fill_manual(values=c("Complete" = "white", "Complete +Mucus" = "#808080", "-G -S" = "white", "-G -S +Mucus"="#ab66ff", "-S"="white", "-S +Mucus"="#ff0366", "-G"="white", "-G +Mucus"="#5770ff", "-T"="white", "-T +Mucus"="#0f7f80")) +
  scale_color_manual(values=c("Complete" = "#808080", "Complete +Mucus" = "#808080", "-G -S" = "#ab66ff", "-G -S +Mucus"="#ab66ff", "-S"="#ff0366", "-S +Mucus"="#ff0366", "-G"="#5770ff", "-G +Mucus"="#5770ff", "-T"="#0f7f80", "-T +Mucus"="#0f7f80")) +
  annotate(geom="text", x= 1.5, y=max(all_cond_biomass$Biomass), label="****", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 3.5, y=max(all_cond_biomass$Biomass), label="**", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 5.5, y=max(all_cond_biomass$Biomass), label="**", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 7.5, y=max(all_cond_biomass$Biomass), label="**", hjust="center", vjust="top", size=8) + 
  annotate(geom="text", x= 9.5, y=max(all_cond_biomass$Biomass), label="p=0.0885", hjust="center", vjust="top", size=4)
all_biomass_vplot
ggsave(file="All_Cond_Biomass.svg", plot=all_biomass_vplot, width=12, height=4, dpi=300)
```
